### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by eurunuela** [jmairal/arsenic#6]
Hi Julien,

I've tried the package (OpenBlas version) on two different clusters with Python 3.6 and 3.7 and keep getting a _segmentation fault_ error. 

In one of the clusters I get the following error message:

```
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'python/python3.7'
job_scripts/4130: line 11:   676 Segmentation fault      (core dumped)
```
In the other cluster I only get the segmentation fault message.

Is this error due to an issue during installation of the package? Or is there some kind of bug that's causing it?

I need to run 50 optimization problems (cyanure calls) in parallel to do some kind of bootstrapping, thus the need for cyanure to work on a cluster.

Thank you!

**Comment by jmairal** [comment]
Hi,

could you tell me 
   - which OS is running on these clusters 
   - which version of gcc was used ?

Best

Julien

**Comment by eurunuela** [comment]
The OS on one of the clusters is _CentOS Linux release 7.4.1708 (Core)_

This is the gcc version:

```
Using built-in specs. 
COLLECT_GCC=gcc 
C​O​L​L​E​C​T​_​L​T​O​_​W​R​A​P​P​E​R​=​/​u​s​r​/​l​i​b​e​x​e​c​/​g​c​c​/​x​8​6​_​6​4​-​r​e​d​h​a​t​-linux/4.8.5/lto-wrapper 
Target: x86_64-redhat-linux 
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu -​-​e​n​a​b​l​e​-​l​a​n​g​u​a​g​e​s​=​c​,​c​+​+​,​o​b​j​c​,​o​b​j​-​c​+​+​,​j​a​v​a​,​f​o​r​t​r​a​n​,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj -​-​w​i​t​h​-​i​s​l​=​/​b​u​i​l​d​d​i​r​/​b​u​i​l​d​/​B​U​I​L​D​/​g​c​c​-​4​.​8​.​5​-​2​0​1​5​0​7​0​2/obj-x86_64-redhat-linux/isl-install -​-​w​i​t​h​-​c​l​o​o​g​=​/​b​u​i​l​d​d​i​r​/​b​u​i​l​d​/​B​U​I​L​D​/​g​c​c​-​4​.​8​.​5​-​2​0​1​5​0​702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux 
Thread model: posix 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
```

**Comment by jmairal** [comment]
This is what I suspected. We also had a similar problem here with CentOS, which is shipped with gcc 4.x.  For some reason, the toolbox requires gcc 5.x at least (the latest one being gcc 7.4).

If you find a way to install gcc 5, 6 or 7 on CentOS, it **may** work. In the meantime, I will try to make the toolbox work with gcc 4.

**Comment by jmairal** [comment]
The good news is that I managed to install Centos7 on a virtual machine and I could reproduce the issue. First step before solving it...

**Comment by jmairal** [comment]
Here is what worked for me, from Cyanure's repository, on Anaconda 
  - sudo yum install centos-release-scl
  - sudo yum install devtoolset-7
  - scl enable devtoolset-7 bash
  - rm -rf build/
  - python setup_cyanure_mkl.py install

I suspect that gcc 4.8 is not fully compatible with c++11.

**Comment by eurunuela** [comment]
Hi Julien,

I have tried with gcc 7.3.0 on both clusters and still get the segmentation fault with the OpenBlas version of _Cyanure_.

**Comment by jmairal** [comment]
I am now trying to reproduce the bug, but so far it works with gcc 7.3 on my centos 7 (and fails with gcc 4.8).
  - are you using anaconda or the default python distribution shipped with centos ?
  - could you give me the output of  np.show_config() ?

**Comment by eurunuela** [comment]
I am using anaconda.

The output of `np.show_config()` is the following:

```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by jmairal** [comment]
This is strange since Anaconda is supposed to be linked to mkl by default. It is linked to openblas only when you install the openblas and nomkl packages.  This output is the one I obtained from the default python distribution on Centos 7.

The bad news is that I cannot reproduce the problem on my virtual machine. As soon as I switch to gcc 7.3, the problem disappears, and I manage to make the package work both on Anaconda and on the regular python distribution.

The good news is that a student of mine is having a similar problem as you on a shared CentOS-based cluster. We should be able to dig into the problem on Friday. In the meantime, I am wondering if I could send you directly a precompiled wheel that has been compiled on my CentOS and see if it works on yours.

**Comment by jmairal** [comment]
So here is a precompiled wheel for python 3.6 
http://thoth.inrialpes.fr/people/mairal/cyanure_openblas-0.2-cp36-cp36m-linux_x86_64.whl 
which you can install with pip3 install.

If you still get the segfault, we will try to solve the issue on Friday, since we have a platform similar to yours with potentially the same issue.

**Comment by eurunuela** [comment]
Thank you Julien!

I will let you know if it works.

**Comment by eurunuela** [comment]
Thank you Julien!

I will let you know if it works.

**Comment by eurunuela** [comment]
I'm getting the following error:

```
    [root@ipsnode-7-0 ~]# pip install
    cyanure_openblas-0.2-cp36-cp36m-linux_x86_64.whl 
    cyanure_openblas-0.2-cp36-cp36m-linux_x86_64.whl is not a supported
    wheel on this platform.
    [root@ipsnode-7-0 ~]#
```

**Comment by jmairal** [comment]
I may have a version of CentOS which is slightly more recent than yours.

A last possibility would be to try compiling the toolbox after installing the package gxx_linux-64
which is available with Anaconda. It seems to come with gcc 7.3

Otherwise, we will investigate the issue on Friday.

**Comment by eurunuela** [comment]
I was able to install it in one of the clusters but I cannot use it because the numpy version is not the same.

Could you please tell me what numpy version you used?

Thanks!

**Comment by jmairal** [comment]
1.18.1

**Comment by eurunuela** [comment]
Hi Julien,

Unfortunately we were not able to make the precompiled version work (i.e. not to get a segfault) with Python 3.6.6 and numpy 1.18.1.

I hope you can find a solution.

Thanks!

**Comment by jmairal** [comment]
Here is where we stand up regarding your problem

* a student of mine had a similar issue as yours on a CentOS cluster, which could be summarized as
  - segfault when Cyanure is compiled with gcc 4.8.5
  - difficulties to install gcc 7.x
  - same np.show_config() as yours that did not seem consistent to me for an Anaconda environment.

* on Friday, we looked again at the problem, but in the meantime, the admin of the cluster had upgraded Centos to a more recent version (7.7.1908), and we could install Cyanure by following simple steps described below. The inconsistency of np.show_config() had also disappeared. Then, I installed Centos 7.4.1708 on a virtual machine and the steps described below seem to work as well.
  
* on the consistency of np.show_config(). By default, Anaconda uses MKL, and np.show_config() should contain things such as
  blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda/include']

   If instead, I want to use openblas, I create a new environment
   conda create --name openblas python=3.6     <- do not forget python=3.6 here, otherwise ``python'' may simply call the default python distribution from the system and not anaconda (this is what happens on my CentOS).
   conda activate openblas
   conda install numpy nomkl openblas scipy
   Then, np.show_config() gives
   blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/anaconda/envs/openblas/lib']   <- note that the path points to the openblas package; this is important
    language = c
    define_macros = [('HAVE_CBLAS', None)]

   If I do not want to use Anaconda, I may get out of the conda environment and call the ``system'' python. Then I get,
   blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']    <- note here that the path does not point to any openblas package.
    language = c
    define_macros = [('HAVE_CBLAS', None)]

=> It seems that there was something a bit fishy between CentOS and Anaconda at some point, where we believe to call Anaconda, but we call instead the ``system'' python,
or ``system'' libraries.

* Steps that worked for us (both for mkl and openblas, but below is the example for openblas.
   conda create --name openblas python=3.6
   conda activate openblas
   conda install numpy nomkl openblas scipy
   conda install gxx_linux-64      (simplest way to install gcc 7.3)
   git clone https://github.com/jmairal/cyanure.git 
   cd cyanure
   python setup_cyanure_openblas.py install
   wget http://pascal.inrialpes.fr/data2/mairal/data/covtype.npz
   mkdir data
   mv covtype.npz data/
   python test.py --dataset covtype --penalty l2 --loss logistic --solver auto --lambd 0.1
   
* Note that we also found a stupid bug leading to a segfault whenever the number of epochs is smaller than it0 (10 by default). We will push the correction at the beginning of next week.

**Comment by eurunuela** [comment]
Hello Julien,

I'm sorry it took me this long to get back to you. We've been trying different ways of installing Cyanure and have decided to use a singularity container where we are sure the package works. I will try to make the container work in my own pipeline now but I believe it should be fine.

I hope you get to solve this issue soon, as the package is very useful in my opinion.

Shall we leave this issue open in case other users have the same issue?

Thank you very much for you help!

**Comment by jmairal** [comment]
Hi,

let us the issue open, in case someone else encounters the same problem. 
Unfortunately, we were not able to reproduce the bug on several versions of CentOS 7 (but i am pretty sure we had it in the past before a recent OS upgrade).

My feeling is that it is somewhat related to gcc 4.8.5 (you get a segfault with it, regardless of the OS), which may be due to a poor support of C++11.

**Comment by jmairal** [comment]
Hi,

some news about this issue:   did you install numpy by using pip install or  conda install ?

**Comment by eurunuela** [comment]
Hi,

We installed them with conda. These are the versions: `numpy=1.18.1=py36h94c655d_0` and `numpy-base=1.18.1=py36h2f8d375_1`.

**Comment by jmairal** [comment]
The reason i asked is that the output of your np.show_config() suggested that numpy was installed with pip.  (or updated by pip when installing another package), which leads to some issues.

**Comment by danifranco** [comment]
Hello,

I have the same issue here:

I have installed a fresh Singularity container with Centos 7.7.1908, as you mentioned, and the second test of the tutorial gives me 'Segmentation fault' also. The test used is this:

```
import cyanure as cyan
import numpy as np
import scipy.sparse
#load rcv1 dataset about 1Gb, n=781265, p=47152
data = np.load('data/rcv1.npz',allow_pickle=True); y=data['y']; X=data['X']
X = scipy.sparse.csc_matrix(X.all()).T # n x p matrix, csr format
#normalize the rows of X in-place, without performing any copy
cyan.preprocess(X,normalize=True,columns=False)
#declare a binary classifier for squared hinge loss + l1 regularization
classifier=cyan.BinaryClassifier(loss='sqhinge',penalty='l2')
# uses the auto solver by default, performs at most 500 epochs
classifier.fit(X,y,lambd=0.000005,max_epochs=500,tol=1e-3)
```

The steps made were these:

- Prepare the OS:
```
yum update -y
yum install -y wget git which
mkdir -p /installations/test/data
cd /installations
```

- Anaconda installation:
```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
bash miniconda.sh -b -p /installations/miniconda
```

- Set up a conda environment (as you described in https://github.com/jmairal/cyanure/issues/6#issuecomment-590073542):
```
source /installations/miniconda/etc/profile.d/conda.sh
conda create --name openblas python=3.6
conda activate openblas
conda install numpy nomkl openblas scipy
conda install gxx_linux-64
```

- Cyanure installation:
```
git clone https://github.com/jmairal/cyanure.git
cd cyanure
python setup_cyanure_openblas.py install
```

- Prepare the data and run the test:
```
cd /installations/test
wget http://pascal.inrialpes.fr/data2/mairal/data/rcv1.npz
mv rcv1.npz data/
source /installations/miniconda/etc/profile.d/conda.sh
conda activate openblas
python test.py
#14673 Segmentation fault      (core dumped) python test.py
```
# Checks:
- OS version:
```
cat /etc/system-release
CentOS Linux release 7.7.1908 (Core)
```
- Python used:
```
which python
/installations/miniconda/envs/openblas/bin/python
```
- Packages installed with in the env:
```
name: openblas
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=openblas
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_1
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.6=h5a2b251_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - nomkl=3.0=0
  - numpy=1.18.1=py36h94c655d_0
  - numpy-base=1.18.1=py36h2f8d375_1
  - openblas=0.3.6=2
  - openblas-devel=0.3.6=2
  - openssl=1.1.1e=h7b6447c_0
  - pip=20.0.2=py36_1
  - python=3.6.10=hcf32534_1
  - readline=8.0=h7b6447c_0
  - scipy=1.4.1=py36habc2bb6_0
  - setuptools=46.1.3=py36_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - cyanure-openblas==0.21.post1
prefix: /installations/miniconda/envs/openblas
```
- Numpy output:
```
python -c 'import numpy as np; print(np.__version__); print(np.show_config())'
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/installations/miniconda/envs/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/installations/miniconda/envs/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/installations/miniconda/envs/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/installations/miniconda/envs/openblas/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

Thanks a lot for the support!

**Comment by jmairal** [comment]
Thanks! I will give it a try in a virtual machine.
** Update **
I could reproduce the bug

**Comment by jmairal** [comment]
I nailed the issue and will push a correction on git/pipy tonight. It was hard to catch.

**Comment by eurunuela** [comment]
We’ll be happy to test it tomorrow. Thanks a lot!!!

**Comment by jmairal** [comment]
I have pushed some corrections and updated a new package on pypi
I hope it will fix the problem.

The last remaining issue we spot, which could create compilation problems is when you use Anaconda/Miniconda, and then later update numpy via pip (which may occur if you install a package via pip that requires a specific version of numpy), but this should not occur very often.

**Comment by danifranco** [comment]
Thanks a lot, it works now!

**Comment by jmairal** [comment]
Thanks @danifranco and @eurunuela for the bug report and helping me reproduce the bug. I think I can close it now.

**Comment by eurunuela** [comment]
Even though the tests passed, I still get the segmentation error in my pipeline. Is it okay if I share my data and design matrices via email, along with the command I use?

**Comment by jmairal** [comment]
sure, this will be useful.

Julien

**Comment by eurunuela** [comment]
Perfect, I just emailed you.
